name: Coverage
on:
  push:
      branches:
          - 'dev'
          - 'dev-sim'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y lcov make
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Generate Coverage
        run: |
          make coverage
          cd tests
          make coverage
          lcov --directory . --zerocounters
          source testMagAOX.bash
          cd ..
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info "*/apps/*/tests/*" "/usr/*" "/sys/*" "/tty/*" --output-file coverage_filtered.info
          genhtml coverage_filtered.info --output-directory coverage_report --title "MagAOX"
      - name: Add SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh
            echo "xwcl.science ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAqGanUWS9Wb34oCHCDX2xqhlCstMTN9c0oFoKJkYtZ3" >> /home/runner/.ssh/known_hosts
            echo "${{ secrets.DEPLOY_GARY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add /home/runner/.ssh/github_actions
      - name: Sync to magao-x.org
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            rsync -rz --delete coverage_report/ gary@xwcl.science:/srv/www/main/docs/coverage/
